# Generated by Django 5.1.5 on 2026-02-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_events', '0003_eventtickettype_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
