name: "Install python dependencies"
description: "Install python dependencies"
inputs:
  python-version:
    description: "The python version"
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Install dependencies
      working-directory: ./backend
      run: pip install -r requirements/development.txt
      shell: bash
