name: ticketera-popular-backend-resources

services:
  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    volumes:
      - db:/var/lib/postgresql/data_16
volumes:
  db:
    driver: local
