# Generated by Django 5.1.5 on 2025-01-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
