underground_venues = [
    "El Refugio Sonoro",
    "Casa cultural Victor Jara",
    "Centro Cultural Raymundo Gleyzer",
    "Espacio Perfección",
    "Subterráneo Bar",
    "Teatro Espectral",
    "La Fábrica Oculta",
    "Noctámbulos Club",
    "Espacio Ruido",
    "El Sótano Creativo",
    "Galería Efímera",
    "Vórtice Cultural",
    "Caverna del Arte",
    "Neón & Sombras",
    "Colectivo Anómalo",
    "El Desván del Caos",
    "Distrito Experimental",
    "La Cripta Electrónica",
    "Oculto Teatro Bar",
    "Fuego y Metal",
    "El Último Búnker",
    "Ritual Urbano",
    "Círculo Secreto",
    "Averno Club",
    "La Caja Negra",
    "El Umbral Rojo",
    "Noche Subterránea",
    "El Espejo Roto",
    "Marea Alternativa",
    "El Subsuelo del Arte",
    "Dimensión Desconocida",
    "Punto de Fuga",
    "Simbiosis Cultural",
    "El Faro Perdido",
    "Laberinto Sonoro",
    "Luz de Gas",
    "El Inframundo Bar",
    "Caja de Pandora",
    "Refugio Anónimo",
    "Ecos del Pasado",
    "Cripta Subterránea",
    "Espectros del Jazz",
    "El Teatro Invisible",
]
