culture_events = [
    "Noctámbulos Fest",
    "Subterráneo Sonoro",
    "Arte Oculto Sessions",
    "Ritual Urbano",
    "Neón y Ruinas",
    "Ruido y Rebelión",
    "Tinta y Concreto",
    "Círculo Secreto",
    "Fronteras Invisibles",
    "Vórtice Cultural",
    "Códigos Perdidos",
    "Electro Ancestral",
    "Resistencia Sonora",
    "Ecos del Subsuelo",
    "Espectros de la Noche",
    "Laberinto Creativo",
    "Underground Chronicles",
    "Anomalía Fest",
    "Híbridos Sonoros",
    "Distorsión Colectiva",
]
