name: Backend checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_missing_migrations:
    name: Check missing migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-dependencies
        with:
          python-version: "3.10"
      - name: Check missing migrations
        env:
          DJANGO_SETTINGS_MODULE: ticket_manager.settings.testing
        working-directory: ./backend/ticket_manager
        run: python manage.py makemigrations --dry-run --check --no-input
  build:
    name: Django tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"] # Conviene testear la versión actual y futura
    # Service containers to run with `container-job`
    services:
      postgres:
        image: postgres:16.0-alpine
        env:
          POSTGRES_PASSWORD: docker
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-dependencies
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with django
        env:
          DJANGO_SETTINGS_MODULE: ticket_manager.settings.testing
        working-directory: ./backend/ticket_manager
        run: pytest
