# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_missing_migrations:
    name: Check missing migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements/development.txt
      - name: Check missing migrations
        env:
          DJANGO_SETTINGS_MODULE: ticket_manager.settings.testing
        run: |
          cd backend/ticket_manager
          python manage.py makemigrations --dry-run --check --no-input
  run_pre_commit:
    name: Run pre-commit in all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements/development.txt
      - name: Run pre-commit
        run: |
          cd backend
          pre-commit run --all-files
  build:
    name: Django tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"] # Conviene testear la versión actual y futura
    # Service containers to run with `container-job`
    services:
      postgres:
        image: postgres:16.0-alpine
        env:
          POSTGRES_PASSWORD: docker
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements/development.txt
      - name: Test with django
        env:
          DJANGO_SETTINGS_MODULE: ticket_manager.settings.testing
        run: |
          cd backend/ticket_manager
          pytest
