name: General checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_pre_commit:
    name: Run pre-commit in all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-dependencies
        with:
          python-version: "3.10"
      - name: Run pre-commit
        working-directory: ./backend
        run: pre-commit run --all-files
