on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  install_python_dependencies:
    name: Install python dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.config-path }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.config-path }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements/development.txt
