culture_events = [
    "Noctámbulos Fest",
    "Subterráneo Sonoro",
    "Arte Oculto Sessions",
    "Ritual Urbano",
    "Neón y Ruinas",
    "Ruido y Rebelión",
    "Tinta y Concreto",
    "Círculo Secreto",
    "Fronteras Invisibles",
    "Vórtice Cultural",
    "Códigos Perdidos",
    "Electro Ancestral",
    "Resistencia Sonora",
    "Ecos del Subsuelo",
    "Espectros de la Noche",
    "Laberinto Creativo",
    "Underground Chronicles",
    "Anomalía Fest",
    "Híbridos Sonoros",
    "Distorsión Colectiva",
]

ticket_types = [
    "Entrada General",
    "Patio",
    "Anticipadas",
    "Socios Club Cultura",
    "Balcón",
    "Gradas",
    "Platea Baja",
    "Platea Alta",
    "Sector A",
    "Sector B",
    "Campo",
    "Pack Familiar",
    "Abono Mensual",
    "Entrada Nocturna",
    "Zona Experiencia",
    "Pase Backstage",
]
